### PR TITLE
html-media-capture: Add separated and latest test report for Safari 10.1

### PR DESCRIPTION
**Pull request by Honry**
For https://github.com/w3c/html-media-capture/issues/7

### CODE REVIEW

**Comment by anssiko** [comment]
Thanks @Honry, LGTM.

**Comment by anssiko** [comment]
(I guess the duplicate column in the report is just a placeholder for the other implementation.)

**Comment by anssiko** [comment]
Or perhaps better to replace the duplicate column with some placeholder text while we wait for the Chromium implementation https://crbug.com/698853 to get updated?

**Review by anssiko — APPROVED** [review]

**Comment by Honry** [comment]
@dontcallmedom, could you help merge this PR?

**Comment by dontcallmedom** [comment]
I've merged it and invited you to the github team that has write access to the repo so that I'm not in the way for a next update :)

Thanks

**Comment by Honry** [comment]
Many thanks, @dontcallmedom.

**Pull request merged**
