### PR TITLE
Update Presentation API Test results

### PR DESCRIPTION
**Pull request by louaybassbouss**
This PR updates the test results of Presentation API. Three Browsers are considered:

* CA61: Chrome Canary for Android Version 61.x.x
* CD59: Chrome for Desktop Version 59.x.x
* FA56: Firefox for Android Version 56.x.x

### CODE REVIEW

**Comment by louaybassbouss** [comment]
@tidoust FYI

**Comment by tidoust** [comment]
Controlling side looks good.

Could you clarify what the columns represent for the receiver results?

I would basically have expected to see:

- `CD59`: Chrome for Desktop Version 59.x.x acting as 1-UA receiver to pilot a Chromecast device
- `FA56`: Firefox for Android Version 56.x.x acting as 1-UA receiver to pilot a Chromecast device

... and my understanding is that `CA61` would not appear as a receiver, because Chrome Canary for Android Version 61.x.x does not come with a 1-UA receiver, and Chromecast devices are not proper receivers either (since they use a proprietary Cast SDK).

Instead, I see `CD53` which seems good (not the same version as the tested controller, but why not) and `CC47` and `CC49` which, for me, do not mean much since Chromecast devices do not implement the receiver side of the Presentation API. Or did I miss an update?

**Comment by markafoltz** [comment]
To clarify, Chromecast devices can act as presentation screens in 1-UA mode (they do not yet implement presentation receiver).

@louaybassbouss Can you answer Francois' other questions?

**Comment by markafoltz** [comment]
Ping @louaybassbouss

**Comment by anssiko** [comment]
Bumping this issue for @louaybassbouss feedback: @tidoust had a question https://github.com/w3c/test-results/pull/107#issuecomment-315792424 looking for an answer.

Ping @Honry to gauge if he'd be available to help. Also looping in @tomoyukilabs.

**Comment by Honry** [comment]
@anssiko, @tidoust's concern on why there's no update for receiving side, sorry, I would like to help but I have no Chromecast in hand.

**Comment by tomoyukilabs** [comment]
If I understand correctly, it seems that the results of controlling UA tests placed in [presentation-api/controlling-ua](https://github.com/w3c/web-platform-tests/tree/master/presentation-api/controlling-ua) are present and up-to-date, but the results of receiving UA tests in [presentation-api/receiving-ua](https://github.com/w3c/web-platform-tests/tree/master/presentation-api/receiving-ua) have not been updated yet.

Can I help you to update the receiver test results?

**Comment by Honry** [comment]
@anssiko, I just got one Chromecast device and can help update the receiver test results at any time.
@tomoyukilabs, please kindly let me know if you are doing the same things. :)

**Comment by Honry** [comment]
I just update the Receiving UA test results at https://github.com/w3c/test-results/pull/111 with `CD59 `and `FA56`.

**Comment by tidoust** [comment]
Thanks @Honry! PR #111 looked good to me, so I went ahead and merged it.

Now, this PR still contains test result updates for the controller side. @louaybassbouss, any chance that you could drop files that touch on the receiving side from this PR so that I can merge the reminder?

**Comment by tidoust** [comment]
@Honry or @tomoyukilabs, any change that one of you could help with updating the test results for the controller side?

**Comment by tomoyukilabs** [comment]
@tidoust First, could you merge this PR for now? Then I would like to submit another PR to update the results of both controller and receiver.

I suppose that wptserver's stash, which is used for communication between controller and receiver, could not often work properly on w3c-test.org, and that would affect the test results. For this reason, I would like to run the tests on my local environment (`./wpt serve`) and update the test report.

**Comment by Honry** [comment]
I am considering if we should deliver an up-to-date test results with latest Browsers, Chrome is now M63 and Firefox Nightly is 57.

**Comment by markafoltz** [comment]
My understanding is that some of the current failures are because of problems with w3c-test.org?  Is the current implementation report valid or does it need to be re-done with a local server?

**Comment by Honry** [comment]
@tomoyukilabs is testing on a local server, and then we will see the difference.

**Pull request merged**
