### PR TITLE
Initial test report for Remote Playback API

### PR DESCRIPTION
**Pull request by Honry**

### CODE REVIEW

**Comment by Honry** [comment]
@avayvod, @mounirlamouri, PTAL.

**Comment by anssiko** [comment]
HTML preview of all results:

https://rawgit.com/Honry/test-results/add-remote-playback/remote-playback/all.html

**Comment by marcoscaceres** [comment]
fancy implementation report is fancy! how can I get one of those for web payments?

**Comment by anssiko** [comment]
@marcoscaceres, https://www.npmjs.com/package/wptreport does the magic for you, just give it JSON data as input :-)

**Comment by mounirlamouri** [comment]
Report lgtm

**Comment by Honry** [comment]
Thanks for the review, I will merge it directly.

**Pull request merged**
