### PR TITLE
Add test report for Chrome on Android

### PR DESCRIPTION
**Pull request by Honry**

### CODE REVIEW

**Comment by Honry** [comment]
@anssiko, PTAL.

**Comment by anssiko** [comment]
Thanks. The following rows that link to the respective test cases should be gray (use `<td class="OK">OK</td>`):

/html-media-capture/capture_audio-manual.html
/html-media-capture/capture_audio_cancel-manual.html
/html-media-capture/capture_fallback_file_upload-manual.html

... similarly to this line:

/html-media-capture/idlharness.html

Other than that, LGTM.

**Comment by Honry** [comment]
I see, gray all the rows of test files. Please check again.

**Comment by anssiko** [comment]
Thanks for the swift update. LGTM.

**Comment by Honry** [comment]
Thank you for reviewing, I am going to merge it.

**Pull request merged**
