### PR TITLE
HTML Media Capture: Mark not implemented tests as 'Not applicable'

### PR DESCRIPTION
**Pull request by Honry**

### CODE REVIEW

**Comment by Honry** [comment]
@anssiko, could you PTAL?

**Comment by anssiko** [comment]
LGTM, with a comment.

Add the following note below the failure analysis paragraph:

>**Not applicable:**
>
>1. /html-media-capture/capture_audio-manual.html
>2. /html-media-capture/capture_audio_cancel-manual.html
>Audio capture is not a normative requirement. The tests are included for completeness and to help future implementations that may want to implement audio capture.

**Comment by Honry** [comment]
@anssiko, thanks for the review, just addressed your comment.

**Comment by anssiko** [comment]
@Honry, LGTM. Thanks!

@dontcallmedom, can you please merge?

**Comment by Honry** [comment]
@anssiko, I think I can merge it directly.

**Pull request merged**
