### PR TITLE
Add Samsung Internet results for Payment Request

### PR DESCRIPTION
**Pull request by poshaughnessy**
As discussed earlier with @marcoscaceres (apologies for the delay!)

Test results run in Samsung Internet for Android v7.2 (stable) and v7.4 (beta). I wasn't sure how to represent minor numbers in the filename, so I went with underscores - happy to change that as desired! (For our browser versioning, we use major numbers for when there is a Chromium engine update, currently a couple of times per year, minor updates include smaller changes but are worth testing separately too).

Thanks!

### CODE REVIEW

**Comment by marcoscaceres** [comment]
Thanks, @poshaughnessy! need a few more days before trying this out (away at a conference this week). Will try to get the results landed next week.

**Comment by marcoscaceres** [comment]
@plehegar see above about version numbers? Any suggestions or best practice?

**Comment by plehegar** [comment]
wptreport excludes based on a RegExp. See https://github.com/w3c/wptreport/blob/master/index.js#L206


I suggest using si72 and si74 for the filename.

**Comment by marcoscaceres** [comment]
@poshaughnessy, could you make the change above to the filenames?

**Comment by poshaughnessy** [comment]
The filename suggestion sounds good to me too - updated now!

**Comment by marcoscaceres** [comment]
Will regenerate soon

**Comment by marcoscaceres** [comment]
Ok, regenerated results 👍  The implementation report is linked directly from the spec: 
https://w3c.github.io/test-results/payment-request/all.html

**Pull request merged**
