### PR TITLE
Add test reports for generic sensor and its concrete sensors

### PR DESCRIPTION
**Pull request by Honry**
Test Platforms: Chrome Canary 67 on Android and Windows Desktop

### CODE REVIEW

**Comment by Honry** [comment]
Ambient Light: http://honry.github.io/test-results/ambient-light/all.html
Accelerometer: http://honry.github.io/test-results/accelerometer/all.html
Generic Sensor: http://honry.github.io/test-results/generic-sensor/all.html
Gyroscope: http://honry.github.io/test-results/gyroscope/all.html
Magnetometer: http://honry.github.io/test-results/magnetometer/all.html
Orientation Sensor: http://honry.github.io/test-results/orientation-sensor/all.html

**Comment by Honry** [comment]
@anssiko, PTAL.

**Review by anssiko — APPROVED** [review]
Thanks!

**Comment by anssiko** [comment]
@Honry, in Generic Sensor all.html, s/sensors/generic-sensor/g

For example:
http://www.w3c-test.org/sensors/SensorErrorEvent-constructor.https.html -> http://www.w3c-test.org/generic-sensor/SensorErrorEvent-constructor.https.html

**Comment by Honry** [comment]
Oops, thanks for capturing this, @anssiko, I will fix in following PR soon.

**Pull request merged**
