### PR TITLE
Add Chrome38 pointer-events results and update report.

### PR DESCRIPTION
**Pull request by RByers**
Note Chrome supports only touch-action, so results for other tests are not included.

### CODE REVIEW

**Comment by RByers** [comment]
I updated the reports by running wptreport -s "Pointer Events".  This made some additional changes that weren't yet reflected.  In particular, the UC10 results were added as all failures.  Robin added the UC10.json in 256c7c855 with a lot of 'PASS' results, but in Jacob's IE submission ff4f1ae2b9 these were changed to FAIL (but still not listed in all.html).  Was this intentional Jacob?

**Comment by jacobrossi** [comment]
The UC10 results in the repo look to have been run using an outdated test suite. As a result, the table wouldn't produce correctly as it didn't have the format for the current tests. I attempted to fix this, but might have messed up in the process--especially if UC10 somehow passes these tests (maybe they use Blink?).  @darobin, where did the initial results come from? Is this an official submission from them? If so, can results from the final test suite be gathered and submitted? If not, can we remove this from the repo?

**Comment by siusin** [comment]
@RByers @jacobrossi 

Please go ahead and delete the UC10 results. Their data won't be helpful to this spec.

**Comment by zqzhang** [comment]
Actually only accepted the .json data at https://github.com/w3c/test-results/commit/0eaf87446ee557ddcd6678ad60d1a5f8a7f0f07c, thanks.

**Pull request closed without merging**
