### PR TITLE
Adding test report files to the payment-request directory

### PR DESCRIPTION
**Pull request by yatri1609**
This PR adds the report files of test runs in Firefox Quantum 62.0 and Chrome 69.0 

This is in accordance with [#54](https://github.com/w3c/payment-method-id/issues/54)

### CODE REVIEW

**Comment by yatri1609** [comment]
@marcoscaceres Can you have a look at these reports ?

**Review by marcoscaceres — CHANGES_REQUESTED** [review]
Ah, forgot another thing. The API only ships in Firefox Nightly. You can grab a copy from https://www.mozilla.org/en-US/firefox/channel/desktop/ 

If you re-enable the “about:config” pref for Payments in Nightly, all these should pass. Then just replace the Firefox file with a new one. I think Firefox Nightly is version 64 currently.

**Comment by marcoscaceres** [comment]
(Sorry about all the typos, doing this on my phone)

**Review by marcoscaceres — APPROVED** [review]
Thanks for running the test again!

**Pull request merged**
