### PR TITLE
Add page-notes results

### PR DESCRIPTION
**Pull request by BigBlueHat**
Probably too little to late...but here is an implementation of the `Choice` feature using the multi-language use case. This code also uses `creator` on bodies to store the software used to create the annotation.

Page Notes is a Web Extension who's code lives at http://github.com/bigbluehat/page-notes

Cheers!
🎩 

/cc @iherman @azaroth42 @tcole3

### CODE REVIEW

**Comment by azaroth42** [comment]
Thanks both! Definitely neither too late nor too little! :)

**Comment by halindrome** [comment]
My question is - what repo was this run against?  Or should I re-run using the input just to make certain we have correct results?

**Comment by BigBlueHat** [comment]
@halindrome these were run against the w3-test.org installation...

I just re-ran these (not in a place to send a PR atm) on the spec-ops.io server and have attached the results to this issue.

I'll review them tomorrow and submit an update (+/- fixes :wink:).

[runner-results.txt](https://github.com/w3c/test-results/files/590932/runner-results.txt) (rename to `.json` if you care to).

**Comment by BigBlueHat** [comment]
And a quick note to show the breakdown of pass/fails from the spec-ops server:
MUSTs: 54/54
Optionals: 12/82
AgentOptionals: 6/36

**Pull request merged**
