### PR TITLE
Presentation api second test report

### PR DESCRIPTION
**Pull request by louaybassbouss**
Second Test report of Presentation API. Following Tests are considered in this test report:
- https://github.com/w3c/web-platform-tests/blob/master/presentation-api/controlling-ua/PresentationConnection_onclosed-manual.html 
- https://github.com/w3c/web-platform-tests/blob/master/presentation-api/controlling-ua/PresentationConnection_onconnected-manual.html  
- https://github.com/w3c/web-platform-tests/blob/master/presentation-api/controlling-ua/PresentationConnection_onterminated-manual.html 
- https://github.com/w3c/web-platform-tests/blob/master/presentation-api/controlling-ua/PresentationRequest_error.html  
- https://github.com/w3c/web-platform-tests/blob/master/presentation-api/controlling-ua/PresentationRequest_success.html  
- https://github.com/w3c/web-platform-tests/blob/master/presentation-api/controlling-ua/getAvailability.html  
- https://github.com/w3c/web-platform-tests/blob/master/presentation-api/controlling-ua/idlharness.html 
- https://github.com/w3c/web-platform-tests/blob/master/presentation-api/controlling-ua/reconnectToPresentation_error-manual.html  
- https://github.com/w3c/web-platform-tests/blob/master/presentation-api/controlling-ua/reconnectToPresentation_success-manual.html
- https://github.com/w3c/web-platform-tests/blob/master/presentation-api/controlling-ua/startNewPresentation_error-manual.html
- https://github.com/w3c/web-platform-tests/blob/master/presentation-api/controlling-ua/startNewPresentation_error.html
- https://github.com/w3c/web-platform-tests/blob/master/presentation-api/controlling-ua/startNewPresentation_success-manual.html
- https://github.com/w3c/web-platform-tests/blob/master/presentation-api/receiving-ua/idlharness.html

### CODE REVIEW

**Comment by louaybassbouss** [comment]
@zqzhang this PR is for the second test report. can you review and merge?

**Comment by louaybassbouss** [comment]
@Honry can you please review and merge.thx

**Comment by Honry** [comment]
@louaybassbouss, I am curious why you don't run the same UAs for both controlling-ua and receiving-ua?

**Comment by louaybassbouss** [comment]
@Honry In the current test results the controlling UA is a chrome browser and receiving ua is a google cast device. We have here 2-UA. Once we have implementation for 1-UA (e.g. Miracast) we will have tests with the same UA on controlling and receiving sides.

**Pull request merged**
